Jamesgit22/Date-on-a-Dime

- .gitignore
- index.html
Added links in html to css style sheet, JS scripts sheet, and jquery 3.6.4. Please review
> Link sheets

- assets/js/scripts.js
Declared 5 arrays globally for date type search parameters for yelp. Also changed line 8 from "var" to "let". Please review.
> More testing with yelp and created date type arrays

- assets/css/style.css
- index.html
Created new html sheet and made changes to css sheet for a new start screen. Please review
> created new home start page for project

- index.html
Added the call to action button.
> call to action button

- assets/css/style.css
- index.html
Changed style of welcome card and shortened welcome message.
> Made changes to clean up welcome message and style of welcome card.

- assets/css/style.css
- assets/js/scripts.js
- index.html
Added JS code for a click event that hides the start screen and calls the screen to ask for user location.
> Start btn event

- assets/css/style.css
- assets/js/scripts.js
- index.html
Created basic style for location input card. Also created custom background color classes in css that can be added to html elements for quick branding. Please review
> updated styling of location input card and added css background classes

- assets/css/style.css
- assets/js/favdates.js
- assets/js/scripts.js
- favdates.html
- index.html
Created new html and js files for housing the users favorite stored dates. Added link to nav bar and check of local storage in main js file. Please review
> Favorites nav/localstore

- assets/js/scripts.js
> Started click events for selecting an indoor or outdoor date

- assets/js/scripts.js
- index.html
> completed weather API link

- assets/js/scripts.js
Added click events for the different types of dates
> Added all button event listeners

- assets/js/scripts.js
Added condition statement to check what type of date the user picked. Also modified yelp call to accept entered city and date type category
> Added logic to check what type of date is selected

- assets/js/scripts.js
- index.html
moved weather html to javascript, created functions out of weather API data fetch, added click listener for search button
> moved weather html to JS

- assets/js/scripts.js
Created function to pick a random category out of an array provided to search in yelp. Also moved button click events inside of correct functions for calling the next screens in the flow of the website. Please review
> Random date

- assets/js/scripts.js
> fixed date category array values to match possible selections

- assets/js/scripts.js
fixed weather api bug, weather data now appears, working on styling
> fixed weather api bug

- assets/js/scripts.js
Fixed bug with fetching the same type of businesses from yelp. Please review.
> Fetch yelp data

- assets/js/scripts.js
> fixed indoor lighthearted button bug

- assets/js/scripts.js
Created function to fetch ratings and reviews for the selected date from yelp API. Also added more comments to code. Changed verbiage in indoor dates card to match possible outcome buttons.
> Successfully getting ratings and reviews from yelp

- assets/css/style.css
- favdates.html
changed color scheme on favdates page
> changed color scheme on favdates page

- assets/js/scripts.js
> Added modal call to all date outcome buttons

- assets/css/style.css
- favdates.html
> Added styling to favorites card

- assets/css/style.css
- assets/js/favdates.js
- assets/js/scripts.js
- favdates.html
added clear all dates button that clears local storage and displayed list items real-time without refreshing page
> added clear button

- assets/js/scripts.js
- favdates.html
- index.html
Replaced all jquery from both javascript files. Also changed top right hand corner link in the favorites page to link back to home screen. Please review
> Replaced Jquery

- assets/css/style.css
- assets/js/scripts.js
- index.html
Added a button to modal called "Try Again" to get a new date of the same category. Please review.
> Added reroll button to modal and javascript to make it function

- assets/css/style.css
- assets/js/scripts.js
- favdates.html
- index.html
> added responsive media queries to webapp for mobile view
